const vocalData = [
    // --- 과학 (Science) ---
    { id: 1, text: "지구는 태양 주위를 공전한다.", pron: "지구는 태양 주위를 공전한다", audio: "appdata/vocalization/audio/1.mp3" },
    { id: 2, text: "빛은 소리보다 훨씬 빠르다.", pron: "비츤 소리보다 훨씬 빠르다", audio: "appdata/vocalization/audio/2.mp3" },
    { id: 3, text: "물은 섭씨 백 도에서 끓는다.", pron: "무른 섭씨 백 또에서 끈는다", audio: "appdata/vocalization/audio/3.mp3" },
    { id: 4, text: "달은 지구의 유일한 위성이다.", pron: "다른 지구의 유일한 위성이다", audio: "appdata/vocalization/audio/4.mp3" },
    { id: 5, text: "모든 물질은 원자로 이루어져 있다.", pron: "모든 물찌른 원자로 이루어져 이따", audio: "appdata/vocalization/audio/5.mp3" },
    { id: 6, text: "식물은 광합성으로 양분을 만든다.", pron: "싱무른 광합썽으로 양부늘 만든다", audio: "appdata/vocalization/audio/6.mp3" },
    { id: 7, text: "에너지는 생성되거나 소멸하지 않는다.", pron: "에너지는 생성되거나 소멸하지 안는다", audio: "appdata/vocalization/audio/7.mp3" },
    { id: 8, text: "뉴턴은 만유인력의 법칙을 발견했다.", pron: "뉴터는 마뉴일려게 법치글 발견해따", audio: "appdata/vocalization/audio/8.mp3" },
    { id: 9, text: "디엔에이는 유전 정보를 담고 있다.", pron: "디에네이는 유전 정보를 담꼬 이따", audio: "appdata/vocalization/audio/9.mp3" },
    { id: 10, text: "지구 온난화는 기후 변화를 일으킨다.", pron: "지구 온난화는 기후 변화를 이르킨다", audio: "appdata/vocalization/audio/10.mp3" },
    { id: 11, text: "태양계에는 여덟 개의 행성이 있다.", pron: "태양계에는 여덜 개의 행성이 이따", audio: "appdata/vocalization/audio/11.mp3" },
    { id: 12, text: "소리는 진동을 통해 전달된다.", pron: "소리는 진동을 통해 전달된다", audio: "appdata/vocalization/audio/12.mp3" },
    { id: 13, text: "뇌는 신경계를 조절하는 기관이다.", pron: "뇌는 신경계를 조절하는 기과니다", audio: "appdata/vocalization/audio/13.mp3" },
    { id: 14, text: "자석의 같은 극끼리는 서로 밀어낸다.", pron: "자서게 가튼 극끼리는 서로 미러낸다", audio: "appdata/vocalization/audio/14.mp3" },
    { id: 15, text: "백신은 전염병 예방에 효과적이다.", pron: "백씨는 저념뼝 예방에 효과저기다", audio: "appdata/vocalization/audio/15.mp3" },
    { id: 16, text: "태양은 스스로 빛을 내는 별이다.", pron: "태양은 스스로 비츨 내는 벼리다", audio: "appdata/vocalization/audio/16.mp3" },
    { id: 17, text: "화석은 과거 생물의 흔적이다.", pron: "화서근 과거 생무레 흔저기다", audio: "appdata/vocalization/audio/17.mp3" },
    { id: 18, text: "산소는 연소와 호흡에 필요하다.", pron: "산소는 연소와 호흐베 피료하다", audio: "appdata/vocalization/audio/18.mp3" },
    { id: 19, text: "은하수는 수많은 별들의 무리다.", pron: "으나수는 수마는 별드레 무리다", audio: "appdata/vocalization/audio/19.mp3" },
    { id: 20, text: "로봇 공학은 날로 발전하고 있다.", pron: "로봇 공하근 날로 발쩐하고 이따", audio: "appdata/vocalization/audio/20.mp3" },
    { id: 21, text: "미세 먼지는 호흡기 건강에 해롭다.", pron: "미세 먼지는 호흡끼 건강에 해롭따", audio: "appdata/vocalization/audio/21.mp3" },
    { id: 22, text: "지진은 지각 변동으로 발생한다.", pron: "지지는 지각 뼌동으로 발쌩한다", audio: "appdata/vocalization/audio/22.mp3" },
    { id: 23, text: "오존층은 자외선을 차단해 준다.", pron: "오존층은 자외서늘 차단해 준다", audio: "appdata/vocalization/audio/23.mp3" },
    { id: 24, text: "인공 지능은 데이터를 통해 학습한다.", pron: "인공 지능은 데이터를 통해 학쓰판다", audio: "appdata/vocalization/audio/24.mp3" },
    { id: 25, text: "상대성 이론은 아인슈타인이 발표했다.", pron: "상대성 이로는 아인슈타이니 발표해따", audio: "appdata/vocalization/audio/25.mp3" },
    { id: 26, text: "빅뱅 이론은 우주의 기원을 설명한다.", pron: "빅뺑 이로는 우주의 기워늘 설명한다", audio: "appdata/vocalization/audio/26.mp3" },
    { id: 27, text: "혈액은 영양소와 산소를 운반한다.", pron: "혀래근 영양소와 산소를 운반한다", audio: "appdata/vocalization/audio/27.mp3" },
    { id: 28, text: "중력은 물체를 지구 중심으로 당긴다.", pron: "중녀근 물체를 지구 중심으로 당긴다", audio: "appdata/vocalization/audio/28.mp3" },
    { id: 29, text: "나비 효과는 작은 변화가 큰 결과를 만든다.", pron: "나비 효과는 작은 변화가 큰 결과를 만든다", audio: "appdata/vocalization/audio/29.mp3" },
    { id: 30, text: "양자 역학은 미시 세계를 다룬다.", pron: "양자 여카근 미시 세계를 다룬다", audio: "appdata/vocalization/audio/30.mp3" },

    // --- 경제 (Economics) ---
    { id: 31, text: "수요가 늘어나면 가격이 오른다.", pron: "수요가 드러나면 가겨기 오른다", audio: "appdata/vocalization/audio/31.mp3" },
    { id: 32, text: "공급이 과하면 가격이 내려간다.", pron: "공그비 과하면 가겨기 내려간다", audio: "appdata/vocalization/audio/32.mp3" },
    { id: 33, text: "인플레이션은 물가 상승을 의미한다.", pron: "인플레이션은 물까 상승을 의미한다", audio: "appdata/vocalization/audio/33.mp3" },
    { id: 34, text: "주식 시장은 경제의 거울이다.", pron: "주식 시장은 경제의 거우리다", audio: "appdata/vocalization/audio/34.mp3" },
    { id: 35, text: "금리는 돈의 가치를 결정한다.", pron: "금니는 도네 가치를 결정한다", audio: "appdata/vocalization/audio/35.mp3" },
    { id: 36, text: "무역은 국가 간의 상품 교환이다.", pron: "무여근 국가 가네 상품 교화니다", audio: "appdata/vocalization/audio/36.mp3" },
    { id: 37, text: "환율은 화폐 사이의 교환 비율이다.", pron: "화뉴른 화폐 사이의 교환 비유리다", audio: "appdata/vocalization/audio/37.mp3" },
    { id: 38, text: "저축은 미래를 위한 투자다.", pron: "저추근 미래를 위한 투자다", audio: "appdata/vocalization/audio/38.mp3" },
    { id: 39, text: "세금은 국가 운영의 기반이 된다.", pron: "세그믄 국가 운영에 기바니 된다", audio: "appdata/vocalization/audio/39.mp3" },
    { id: 40, text: "독점은 시장 경쟁을 저해한다.", pron: "독쩌믄 시장 경쟁을 저해한다", audio: "appdata/vocalization/audio/40.mp3" },
    { id: 41, text: "기회비용은 포기한 것의 가치다.", pron: "기회비용은 포기한 거세 가치다", audio: "appdata/vocalization/audio/41.mp3" },
    { id: 42, text: "GDP는 국내 총생산을 뜻한다.", pron: "지디피는 궁내 총생사늘 뜨탄다", audio: "appdata/vocalization/audio/42.mp3" },
    { id: 43, text: "마케팅은 소비자의 욕구를 파악한다.", pron: "마케팅은 소비자의 욕꾸를 파아칸다", audio: "appdata/vocalization/audio/43.mp3" },
    { id: 44, text: "블록체인은 디지털 장부 기술이다.", pron: "블록체인은 디지털 장부 기수리다", audio: "appdata/vocalization/audio/44.mp3" },
    { id: 45, text: "부동산은 대표적인 실물 자산이다.", pron: "부동사는 대표저긴 실물 자사니다", audio: "appdata/vocalization/audio/45.mp3" },
    { id: 46, text: "보험은 미래의 위험에 대비하는 것이다.", pron: "보허믄 미래의 위허메 대비하는 거시다", audio: "appdata/vocalization/audio/46.mp3" },
    { id: 47, text: "소비 심리는 경기에 영향을 미친다.", pron: "소비 심니는 경기에 영양을 미친다", audio: "appdata/vocalization/audio/47.mp3" },
    { id: 48, text: "스타트업은 혁신적인 아이디어로 시작한다.", pron: "스타트어븐 혁씬저긴 아이디어로 시자칸다", audio: "appdata/vocalization/audio/48.mp3" },
    { id: 49, text: "자본주의는 이윤 추구를 인정한다.", pron: "자본주의는 이윤 추구를 인정한다", audio: "appdata/vocalization/audio/49.mp3" },
    { id: 50, text: "복리는 이자에 이자가 붙는 방식이다.", pron: "봉니는 이자에 이자가 분는 방시기다", audio: "appdata/vocalization/audio/50.mp3" },
    { id: 51, text: "재테크는 자산을 효율적으로 관리하는 것이다.", pron: "재테크는 자사늘 효율쩌그로 괄리하는 거시다", audio: "appdata/vocalization/audio/51.mp3" },
    { id: 52, text: "경기 침체는 생산과 소비가 줄어드는 현상이다.", pron: "경기 침체는 생산과 소비가 주러드는 현상이다", audio: "appdata/vocalization/audio/52.mp3" },
    { id: 53, text: "FTA는 자유 무역 협정을 말한다.", pron: "에프티에이는 자유 무역 협쩡을 마란다", audio: "appdata/vocalization/audio/53.mp3" },
    { id: 54, text: "원자재 가격 상승은 물가에 영향을 준다.", pron: "원자재 가격 쌍승은 물까에 영양을 준다", audio: "appdata/vocalization/audio/54.mp3" },
    { id: 55, text: "신용 등급은 대출 금리에 영향을 미친다.", pron: "신용 등그븐 대출 금리에 영양을 미친다", audio: "appdata/vocalization/audio/55.mp3" },
    { id: 56, text: "유통기한은 상품 판매가 가능한 기간이다.", pron: "유통기하는 상품 판매가 가능한 기가니다", audio: "appdata/vocalization/audio/56.mp3" },
    { id: 57, text: "분산 투자는 위험을 줄이는 방법이다.", pron: "분산 투자는 위허믈 주리는 방버비다", audio: "appdata/vocalization/audio/57.mp3" },
    { id: 58, text: "경제 성장은 삶의 질을 높일 수 있다.", pron: "경제 성장은 살메 지를 노필 수 이따", audio: "appdata/vocalization/audio/58.mp3" },
    { id: 59, text: "최저 임금은 근로자의 생활 안정을 보장한다.", pron: "최저 임그믄 글로자의 생활 안정을 보장한다", audio: "appdata/vocalization/audio/59.mp3" },
    { id: 60, text: "규모의 경제는 생산량이 늘면 비용이 주는 것이다.", pron: "규모의 경제는 생산냥이 늘면 비용이 주는 거시다", audio: "appdata/vocalization/audio/60.mp3" },

    // --- 역사 (History) ---
    { id: 61, text: "세종대왕은 훈민정음을 창제했다.", pron: "세종대왕은 훈민정으믈 창제해따", audio: "appdata/vocalization/audio/61.mp3" },
    { id: 62, text: "이순신 장군은 거북선을 만들었다.", pron: "이순신 장구는 거북써늘 만드러따", audio: "appdata/vocalization/audio/62.mp3" },
    { id: 63, text: "고구려는 광개토대왕 때 영토를 넓혔다.", pron: "고구려는 광개토대왕 때 영토를 널펴따", audio: "appdata/vocalization/audio/63.mp3" },
    { id: 64, text: "신라는 삼국을 통일했다.", pron: "실라는 삼구글 통일해따", audio: "appdata/vocalization/audio/64.mp3" },
    { id: 65, text: "고려 청자는 비색으로 유명하다.", pron: "고려 청자는 비새그로 유명하다", audio: "appdata/vocalization/audio/65.mp3" },
    { id: 66, text: "직지심체요절은 세계 최초 금속 활자본이다.", pron: "직찌심체요저른 세계 최초 금속 활짜보니다", audio: "appdata/vocalization/audio/66.mp3" },
    { id: 67, text: "3.1 운동은 독립 만세 운동이었다.", pron: "사밀 운동은 동님 만세 운동이어따", audio: "appdata/vocalization/audio/67.mp3" },
    { id: 68, text: "안중근 의사는 하얼빈에서 이토를 저격했다.", pron: "안중근 의사는 하얼비네서 이토를 저겨캐따", audio: "appdata/vocalization/audio/68.mp3" },
    { id: 69, text: "팔만대장경은 해인사에 보관되어 있다.", pron: "팔만대장경은 해인사에 보관되어 이따", audio: "appdata/vocalization/audio/69.mp3" },
    { id: 70, text: "첨성대는 동양에서 가장 오래된 천문대다.", pron: "첨성대는 동양에서 가장 오래된 천문대다", audio: "appdata/vocalization/audio/70.mp3" },
    { id: 71, text: "백제는 화려한 문화를 꽃피웠다.", pron: "백쩌는 화려한 문화를 꼳피워따", audio: "appdata/vocalization/audio/71.mp3" },
    { id: 72, text: "조선 왕조 실록은 유네스코 기록 유산이다.", pron: "조선 왕조 실로근 유네스코 기롱 유사니다", audio: "appdata/vocalization/audio/72.mp3" },
    { id: 73, text: "독도는 역사적으로 대한민국의 영토다.", pron: "독또는 역싸저그로 대한민구게 영토다", audio: "appdata/vocalization/audio/73.mp3" },
    { id: 74, text: "석굴암은 통일 신라의 예술적 걸작이다.", pron: "석꾸람은 통일 실라의 예술쩍 껄짜기다", audio: "appdata/vocalization/audio/74.mp3" },
    { id: 75, text: "정조는 수원 화성을 건설했다.", pron: "정조는 수원 화성을 건설해따", audio: "appdata/vocalization/audio/75.mp3" },
    { id: 76, text: "고조선은 단군 왕검이 건국했다.", pron: "고조서는 단군 왕거미 건구캐따", audio: "appdata/vocalization/audio/76.mp3" },
    { id: 77, text: "임진왜란은 1592년에 발발했다.", pron: "임진왜라는 천오백구시비녀네 발발해따", audio: "appdata/vocalization/audio/77.mp3" },
    { id: 78, text: "김구 선생은 대한민국 임시 정부를 이끌었다.", pron: "김구 선생은 대한민국 임시 정부를 이끄러따", audio: "appdata/vocalization/audio/78.mp3" },
    { id: 79, text: "경복궁은 조선의 법궁이다.", pron: "경복꿍은 조선의 법꿍이다", audio: "appdata/vocalization/audio/79.mp3" },
    { id: 80, text: "대동여지도는 김정호가 제작한 지도다.", pron: "대동여지도는 김정호가 제자칸 지도다", audio: "appdata/vocalization/audio/80.mp3" },
    { id: 81, text: "한글은 과학적이고 독창적인 문자다.", pron: "한그른 과학쩌기고 독창저긴 문자다", audio: "appdata/vocalization/audio/81.mp3" },
    { id: 82, text: "발해는 고구려 유민이 세운 나라다.", pron: "바래는 고구려 유미니 세운 나라다", audio: "appdata/vocalization/audio/82.mp3" },
    { id: 83, text: "한국 전쟁은 1950년에 일어났다.", pron: "한국 쩐쟁은 천구백오심녀네 이러나따", audio: "appdata/vocalization/audio/83.mp3" },
    { id: 84, text: "서울 올림픽은 1988년에 개최되었다.", pron: "서울 올림피근 천구백팔씹팔려네 개최되어따", audio: "appdata/vocalization/audio/84.mp3" },
    { id: 85, text: "훈민정음은 백성을 가르치는 바른 소리다.", pron: "훈민정으믄 백썽을 가르치는 바른 소리다", audio: "appdata/vocalization/audio/85.mp3" },
    { id: 86, text: "장영실은 조선 최고의 과학자였다.", pron: "장영시른 조선 최고의 과학짜여따", audio: "appdata/vocalization/audio/86.mp3" },
    { id: 87, text: "을지문덕은 살수대첩을 승리로 이끌었다.", pron: "을찌문더근 살쑤대처블 승리로 이끄러따", audio: "appdata/vocalization/audio/87.mp3" },
    { id: 88, text: "독립문은 자주 독립의 상징이다.", pron: "동님무는 자주 동니베 상징이다", audio: "appdata/vocalization/audio/88.mp3" },
    { id: 89, text: "남대문은 국보 제1호다.", pron: "남대무는 국뽀 제일호다", audio: "appdata/vocalization/audio/89.mp3" },
    { id: 90, text: "유관순 열사는 아우내 장터에서 만세를 불렀다.", pron: "유관순 열사는 아우내 장터에서 만세를 불러따", audio: "appdata/vocalization/audio/90.mp3" },

    // --- 일반/명언 (General) ---
    { id: 91, text: "천천히 가는 것을 두려워 말고 멈추는 것을 두려워하라.", pron: "천천히 가는 거슬 두려워 말고 멈추는 거슬 두려워하라", audio: "appdata/vocalization/audio/91.mp3" },
    { id: 92, text: "실패는 성공을 위한 밑거름이다.", pron: "실패는 성공을 위한 믿꺼르미다", audio: "appdata/vocalization/audio/92.mp3" },
    { id: 93, text: "말 한마디로 천 냥 빚을 갚는다.", pron: "말 한마디로 천 냥 비즐 감는다", audio: "appdata/vocalization/audio/93.mp3" },
    { id: 94, text: "가는 말이 고와야 오는 말이 곱다.", pron: "가는 마리 고와야 오는 마리 곱따", audio: "appdata/vocalization/audio/94.mp3" },
    { id: 95, text: "연습은 배신하지 않는다.", pron: "연스븐 배신하지 안는다", audio: "appdata/vocalization/audio/95.mp3" },
    { id: 96, text: "웃는 얼굴에 침 못 뱉는다.", pron: "운는 얼구레 침 몯 뺀는다", audio: "appdata/vocalization/audio/96.mp3" },
    { id: 97, text: "시작이 반이다.", pron: "시자기 바니다", audio: "appdata/vocalization/audio/97.mp3" },
    { id: 98, text: "건강한 신체에 건전한 정신이 깃든다.", pron: "건강한 신체에 건전한 정시니 긷뜬다", audio: "appdata/vocalization/audio/98.mp3" },
    { id: 99, text: "오늘 할 일을 내일로 미루지 말라.", pron: "오늘 할 리를 내일로 미루지 말라", audio: "appdata/vocalization/audio/99.mp3" },
    { id: 100, text: "꿈을 꾸는 자만이 꿈을 이룰 수 있다.", pron: "꾸믈 꾸는 자마니 꾸믈 이룰 수 이따", audio: "appdata/vocalization/audio/100.mp3" }
];