(function(global){
'use strict';
if(global.__ULIM_MESSAGE_DELIVERY_ADMIN_7355090__)return;
global.__ULIM_MESSAGE_DELIVERY_ADMIN_7355090__=true;
global.ULIM_MESSAGE_DELIVERY_ADMIN_VERSION='2026-08-24.7355090-admin-alimtalk-delivery-history';
var state={rows:[],summary:{},syncCandidates:[],loading:false,autoSyncedKey:''};
function text(v){return String(v==null?'':v).trim();}
function esc(v){return String(v==null?'':v).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#039;');}
function profile(){try{var raw=localStorage.getItem('ulimFirebaseStaffProfile7320')||'';if(raw){var p=JSON.parse(raw);if(p&&typeof p==='object')return p;}}catch(_e){}return global.adminInfo&&typeof global.adminInfo==='object'?global.adminInfo:{};}
function isFullAdmin(){var p=profile(),r=text(p.firebaseRole||p.role||p.adminRole).toLowerCase();return r==='admin'||r==='superadmin'||r==='전체관리자'||r==='전체관리'||r==='원장';}
function room(){return global.ULIM_ROOM_CLASSROOM_REALTIME_728||global.ULIM_ROOM_CLASSROOM_REALTIME_727||global.ULIM_ROOM_CLASSROOM_REALTIME_721||null;}
async function runtime(){var r=room();if(!r||typeof r.preloadRuntime!=='function')throw new Error('Firebase 모듈을 준비하지 못했습니다.');var rt=await r.preloadRuntime();if(!rt||!rt.sdk||!rt.functions)throw new Error('Firebase 관리자 로그인이 필요합니다.');return rt;}
async function call(name,payload){var rt=await runtime(),fn=rt.sdk.httpsCallable(rt.functions,name),res=await fn(payload||{});return res&&res.data||{};}
function today(){var d=new Date();return [d.getFullYear(),String(d.getMonth()+1).padStart(2,'0'),String(d.getDate()).padStart(2,'0')].join('-');}
function monthStart(){return today().slice(0,8)+'01';}
function fmtMs(ms){var d=new Date(Number(ms||0));if(!Number.isFinite(d.getTime()))return '-';return String(d.getMonth()+1).padStart(2,'0')+'/'+String(d.getDate()).padStart(2,'0')+' '+String(d.getHours()).padStart(2,'0')+':'+String(d.getMinutes()).padStart(2,'0');}
function fmtIso(v){var s=text(v);if(!s)return '-';var d=new Date(s);return Number.isFinite(d.getTime())?d.toLocaleString('ko-KR',{hour12:false}):s;}
function typeLabel(t){var m={attendance:'출석',absence:'결석',notice:'공지',daily_evaluation:'일일평가',class_cancel:'휴강',class_substitute:'대강',class_change:'수업일 변경',special_teacher:'특수출석·강사',special_makeup_student:'보강',special_new_move_student:'신규/반이동',checkin:'등원',checkout:'하원',room_confirm:'연습실 승인',room_unavailable:'연습실 사용불가',room_change:'연습실 변경',payment:'결제'};return m[text(t)]||text(t)||'기타';}
function targetLabel(v){return ({student:'학생',parent:'학부모',teacher:'강사',admin:'관리자'})[text(v)]||text(v)||'-';}
function stateLabel(v){return ({delivered:'✅ 전달완료',sending:'🔵 발송중',accepted:'🟡 접수됨',failed:'❌ 발송실패'})[text(v)]||'🟡 접수됨';}
function ensureStyle(){if(document.getElementById('ulimMessageDeliveryStyle7355090'))return;var s=document.createElement('style');s.id='ulimMessageDeliveryStyle7355090';s.textContent='#adminPanelMessageDeliveries .ulim-msg-summary7355090{display:flex;gap:8px;flex-wrap:wrap;margin:12px 0}#adminPanelMessageDeliveries .ulim-msg-chip7355090{padding:8px 11px;border-radius:999px;background:#f1f5f9;font-size:12px;font-weight:900;color:#334155}#adminPanelMessageDeliveries .ulim-msg-table7355090{width:100%;border-collapse:collapse;min-width:860px}#adminPanelMessageDeliveries .ulim-msg-table7355090 th,#adminPanelMessageDeliveries .ulim-msg-table7355090 td{border-bottom:1px solid #e5e7eb;padding:9px 8px;text-align:left;font-size:12px;vertical-align:middle}#adminPanelMessageDeliveries .ulim-msg-table7355090 th{background:#f8fafc;color:#475569;font-weight:900;position:sticky;top:0}#adminPanelMessageDeliveries .ulim-msg-state7355090{font-weight:900;white-space:nowrap}.ulim-msg-failed7355090{color:#b91c1c}.ulim-msg-delivered7355090{color:#15803d}.ulim-msg-sending7355090{color:#1d4ed8}.ulim-msg-accepted7355090{color:#a16207}#ulimMessageDeliveryDetail7355090{display:none;position:fixed;inset:0;background:rgba(15,23,42,.48);z-index:100500;align-items:center;justify-content:center;padding:18px}#ulimMessageDeliveryDetail7355090.open{display:flex}#ulimMessageDeliveryDetail7355090 .card7355090{width:min(720px,96vw);max-height:88vh;overflow:auto;background:#fff;border-radius:16px}#ulimMessageDeliveryDetail7355090 header{display:flex;align-items:center;justify-content:space-between;padding:15px 18px;border-bottom:1px solid #e5e7eb}#ulimMessageDeliveryDetail7355090 main{padding:16px 18px}#ulimMessageDeliveryDetail7355090 .grid7355090{display:grid;grid-template-columns:120px 1fr;gap:8px 12px;font-size:13px}#ulimMessageDeliveryDetail7355090 pre{white-space:pre-wrap;word-break:break-word;background:#f8fafc;border:1px solid #e2e8f0;padding:12px;border-radius:10px;font-family:inherit;font-size:13px;line-height:1.55}@media(max-width:700px){#adminPanelMessageDeliveries .admin-grid{grid-template-columns:1fr!important}#ulimMessageDeliveryDetail7355090 .grid7355090{grid-template-columns:1fr}#adminPanelMessageDeliveries .wrap7355090{overflow-x:auto}}';document.head.appendChild(s);}
function ensureDetail(){var m=document.getElementById('ulimMessageDeliveryDetail7355090');if(m)return m;m=document.createElement('div');m.id='ulimMessageDeliveryDetail7355090';m.innerHTML='<section class="card7355090"><header><b>알림톡 발송 상세</b><button type="button" class="admin-btn gray" data-close7355090="1">닫기</button></header><main id="ulimMessageDeliveryDetailBody7355090"></main></section>';m.addEventListener('click',function(e){if(e.target===m||(e.target.closest&&e.target.closest('[data-close7355090="1"]')))m.classList.remove('open');});document.body.appendChild(m);return m;}
function filters(){function v(id){var el=document.getElementById(id);return text(el&&el.value);}return {startDate:v('msgDeliveryStart7355090'),endDate:v('msgDeliveryEnd7355090'),type:v('msgDeliveryType7355090'),state:v('msgDeliveryState7355090'),search:v('msgDeliverySearch7355090'),limit:500};}
function loading(on,msg){state.loading=!!on;var el=document.getElementById('msgDeliveryStatus7355090');if(el)el.textContent=msg||'';['msgDeliverySearchBtn7355090','msgDeliveryRefreshBtn7355090'].forEach(function(id){var b=document.getElementById(id);if(b)b.disabled=!!on;});}
function renderSummary(){var el=document.getElementById('msgDeliverySummary7355090');if(!el)return;var s=state.summary||{};el.innerHTML='<span class="ulim-msg-chip7355090">전체 '+Number(s.total||0)+'건</span><span class="ulim-msg-chip7355090">✅ 전달완료 '+Number(s.delivered||0)+'</span><span class="ulim-msg-chip7355090">🔵 발송중 '+Number(s.sending||0)+'</span><span class="ulim-msg-chip7355090">🟡 접수됨 '+Number(s.accepted||0)+'</span><span class="ulim-msg-chip7355090">❌ 실패 '+Number(s.failed||0)+'</span>';}
function render(){renderSummary();var w=document.getElementById('msgDeliveryTableWrap7355090');if(!w)return;if(!state.rows.length){w.innerHTML='<div style="padding:26px;text-align:center;color:#64748b">조회된 알림톡 발송내역이 없습니다.</div>';return;}var h='<div class="wrap7355090"><table class="ulim-msg-table7355090"><thead><tr><th>발송일시</th><th>학생</th><th>종류</th><th>수신대상</th><th>번호</th><th>상태</th><th>결과</th><th></th></tr></thead><tbody>';state.rows.forEach(function(r,i){h+='<tr><td>'+esc(fmtMs(r.createdAtMs))+'</td><td><b>'+esc(r.studentName||'-')+'</b></td><td>'+esc(typeLabel(r.type))+'</td><td>'+esc(targetLabel(r.recipientTarget))+'</td><td>'+esc(r.phoneMasked||'-')+'</td><td><span class="ulim-msg-state7355090 ulim-msg-'+esc(r.state||'accepted')+'7355090">'+esc(stateLabel(r.state))+'</span></td><td>'+esc(r.statusCode||'-')+(r.reason?' · '+esc(r.reason):'')+'</td><td><button type="button" class="admin-btn gray" data-detail7355090="'+i+'">상세</button></td></tr>';});w.innerHTML=h+'</tbody></table></div>';Array.from(w.querySelectorAll('[data-detail7355090]')).forEach(function(b){b.onclick=function(){detail(Number(b.getAttribute('data-detail7355090')));};});}
function detail(i){var r=state.rows[i];if(!r)return;var m=ensureDetail(),b=document.getElementById('ulimMessageDeliveryDetailBody7355090');b.innerHTML='<div class="grid7355090"><b>학생</b><span>'+esc(r.studentName||'-')+'</span><b>발송종류</b><span>'+esc(typeLabel(r.type))+'</span><b>수신대상</b><span>'+esc(targetLabel(r.recipientTarget))+'</span><b>수신번호</b><span>'+esc(r.phoneMasked||'-')+'</span><b>상태</b><span>'+esc(stateLabel(r.state))+'</span><b>SOLAPI 코드</b><span>'+esc(r.statusCode||'-')+'</span><b>결과사유</b><span>'+esc(r.reason||'-')+'</span><b>Message ID</b><span>'+esc(r.messageId||'-')+'</span><b>발송요청</b><span>'+esc(fmtMs(r.createdAtMs))+'</span><b>처리시각</b><span>'+esc(fmtIso(r.dateProcessed))+'</span><b>결과보고</b><span>'+esc(fmtIso(r.dateReported))+'</span><b>단말수신</b><span>'+esc(fmtIso(r.dateReceived))+'</span></div><h4 style="margin:18px 0 8px">발송문구</h4><pre>'+esc(r.messageText||'SOLAPI 상태 갱신 후 발송문구를 확인할 수 있습니다.')+'</pre>';m.classList.add('open');}
async function refresh(){if(state.loading)return;var ids=Array.from(new Set(state.rows.map(function(r){return text(r.deliveryId);}).filter(Boolean))).slice(0,100);if(!ids.length)return;loading(true,'SOLAPI 실제 전송 상태를 확인하는 중...');try{await call('refreshMessageDeliveryStatusesAdmin7355090',{deliveryIds:ids});loading(false,'');await load(false);}catch(e){loading(false,text(e&&e.message)||'SOLAPI 상태를 갱신하지 못했습니다.');}}
async function load(autoSync){if(!isFullAdmin()||state.loading)return;loading(true,'알림톡 발송내역을 불러오는 중...');try{var d=await call('listMessageDeliveriesAdmin7355090',filters());state.rows=Array.isArray(d.rows)?d.rows:[];state.summary=d.summary||{};state.syncCandidates=Array.isArray(d.syncCandidates)?d.syncCandidates:[];render();loading(false,'Firestore 발송기록 기준 · SOLAPI 최종 상태를 함께 표시합니다.');var k=filters().startDate+'|'+filters().endDate+'|'+state.syncCandidates.join(',');if(autoSync!==false&&state.syncCandidates.length&&state.autoSyncedKey!==k){state.autoSyncedKey=k;loading(true,'접수/발송중 건의 SOLAPI 최종 상태를 확인하는 중...');await call('refreshMessageDeliveryStatusesAdmin7355090',{deliveryIds:state.syncCandidates.slice(0,100)});loading(false,'');return load(false);}}catch(e){state.rows=[];state.summary={};render();loading(false,text(e&&e.message)||'알림톡 발송내역을 불러오지 못했습니다.');}}
function defaults(){ensureStyle();var s=document.getElementById('msgDeliveryStart7355090'),e=document.getElementById('msgDeliveryEnd7355090');if(s&&!s.value)s.value=monthStart();if(e&&!e.value)e.value=today();var q=document.getElementById('msgDeliverySearch7355090');if(q&&!q.dataset.bound7355090){q.dataset.bound7355090='1';q.addEventListener('keydown',function(ev){if(ev.key==='Enter')load(true);});}var b=document.getElementById('msgDeliverySearchBtn7355090');if(b)b.onclick=function(){load(true);};var r=document.getElementById('msgDeliveryRefreshBtn7355090');if(r)r.onclick=refresh;}
async function enter(){if(!isFullAdmin())return;defaults();await load(true);}
global.ULIM_MESSAGE_DELIVERY_ADMIN_7355090={enter:enter,reload:function(){return load(true);},refreshStatus:refresh};
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',defaults,{once:true});else defaults();
})(typeof window!=='undefined'?window:globalThis);
