
window.__ULIM_NEW_STUDENT_ADMIN_ENHANCER_73550954__ = true;
(function(global){
  'use strict';
  const MARK='[[ULIMNS53]]';
  const END='[[/ULIMNS53]]';
  const STYLE='ulimNs53AdminStyle';
  function text(v){return String(v==null?'':v).trim();}
  function esc(v){return String(v==null?'':v).replace(/[&<>"']/g, s=>({ '&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;' }[s]));}
  function style(){ if(document.getElementById(STYLE)) return; const s=document.createElement('style'); s.id=STYLE; s.textContent='\n.ulim-ns53-admin-box{margin-top:12px;padding:12px;border:1px solid #dbe4ef;border-radius:12px;background:#f8fffb}.ulim-ns53-admin-box h5{margin:0 0 10px;font-size:14px}.ulim-ns53-admin-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:8px}.ulim-ns53-admin-wide{grid-column:1/-1}.ulim-ns53-admin-item{border:1px solid #dbe4ef;border-radius:10px;padding:10px;background:#fff;margin-top:8px}.ulim-ns53-admin-item .row{display:grid;grid-template-columns:1fr 1fr;gap:8px}.ulim-ns53-admin-item input,.ulim-ns53-admin-item textarea,.ulim-ns53-admin-select{width:100%;border:1px solid #cbd5e1;border-radius:8px;padding:8px}.ulim-ns53-admin-item textarea{min-height:86px;resize:vertical}.ulim-ns53-admin-toolbar{display:flex;gap:8px;flex-wrap:wrap;margin-top:10px}.ulim-ns53-admin-toolbar button{border:0;border-radius:8px;padding:8px 12px;font-weight:800;background:#e2e8f0}.ulim-ns53-admin-toolbar .green{background:#16a34a;color:#fff}.ulim-ns53-admin-toolbar .red{background:#fee2e2;color:#b91c1c}'; document.head.appendChild(s); }
  function parseMeta(body){ body=text(body); const a=body.indexOf(MARK), b=body.indexOf(END); if(a<0||b<a) return null; const json=body.slice(a+MARK.length,b).trim(); const rest=body.slice(b+END.length).trim(); try{ const meta=JSON.parse(json); meta.__rest=rest; return meta; }catch(_e){ return null; } }
  function serialize(meta, rest){ return MARK+'\n'+JSON.stringify(meta,null,2)+'\n'+END+'\n'+text(rest||''); }
  function pageRows(){ return Array.from(document.querySelectorAll('#nrAcademyPages73550937 [data-page-index]')); }
  function ensureOnRow(row){ if(row.querySelector('.ulim-ns53-admin-box')) return; style(); const bodyField=row.querySelector('[data-page-field="body"]'); if(!bodyField) return; const current=parseMeta(bodyField.value)||{type:'generic',items:[],__rest:bodyField.value||''}; const box=document.createElement('div'); box.className='ulim-ns53-admin-box'; box.innerHTML='<h5>강사소개 / 반별 커리큘럼 전용 표시</h5><div class="ulim-ns53-admin-grid"><div><label>페이지 유형</label><select class="ulim-ns53-admin-select" data-ns53-type><option value="generic">일반 페이지</option><option value="teachers">강사소개 카드형</option><option value="curriculum">반별 커리큘럼 버튼형</option></select></div><div><label>설명 문구</label><input data-ns53-rest value="'+esc(current.__rest||'')+'"></div></div><div data-ns53-items></div><div class="ulim-ns53-admin-toolbar"><button type="button" data-ns53-add>항목 추가</button><button type="button" class="green" data-ns53-pack>본문에 반영</button></div>';
    row.appendChild(box); const typeSel=box.querySelector('[data-ns53-type]'); typeSel.value=current.type||'generic'; const itemsHost=box.querySelector('[data-ns53-items]');
    function renderItems(){ const meta=parseMeta(bodyField.value)||current; const type=typeSel.value; const items=Array.isArray(meta.items)?meta.items:[]; if(type==='generic'){ itemsHost.innerHTML='<div style="margin-top:8px;color:#64748b;font-size:12px">일반 페이지는 기존 제목/이미지/내용 필드만 사용합니다.</div>'; return; }
      itemsHost.innerHTML=items.map((item,idx)=>{ if(type==='teachers') return '<div class="ulim-ns53-admin-item" data-ns53-item="'+idx+'"><div class="row"><input placeholder="강사명" data-f="name" value="'+esc(item.name||'')+'"><input placeholder="한줄소개" data-f="summary" value="'+esc(item.summary||'')+'"></div><div class="row" style="margin-top:8px"><input placeholder="프로필 이미지 URL" data-f="imageUrl" value="'+esc(item.imageUrl||'')+'"><input placeholder="표시순서용 메모(선택)" data-f="memo" value="'+esc(item.memo||'')+'"></div><textarea class="ulim-ns53-admin-wide" placeholder="상세 설명" data-f="detail" style="margin-top:8px">'+esc(item.detail||'')+'</textarea><div class="ulim-ns53-admin-toolbar"><button type="button" class="red" data-ns53-remove="'+idx+'">삭제</button></div></div>';
        return '<div class="ulim-ns53-admin-item" data-ns53-item="'+idx+'"><div class="row"><input placeholder="반 ID 또는 키" data-f="classId" value="'+esc(item.classId||'')+'"><input placeholder="표시명" data-f="label" value="'+esc(item.label||'')+'"></div><div class="row" style="margin-top:8px"><input placeholder="커리큘럼 이미지 URL" data-f="imageUrl" value="'+esc(item.imageUrl||'')+'"><input placeholder="한줄소개(선택)" data-f="summary" value="'+esc(item.summary||'')+'"></div><textarea class="ulim-ns53-admin-wide" placeholder="상세 설명" data-f="detail" style="margin-top:8px">'+esc(item.detail||'')+'</textarea><div class="ulim-ns53-admin-toolbar"><button type="button" class="red" data-ns53-remove="'+idx+'">삭제</button></div></div>'; }).join('');
      itemsHost.querySelectorAll('[data-ns53-remove]').forEach(btn=>btn.onclick=()=>{ const next=readItems().filter((_,i)=>i!==Number(btn.dataset.ns53Remove)); bodyField.value=serialize({type:typeSel.value,items:next}, box.querySelector('[data-ns53-rest]').value); renderItems(); });
    }
    function readItems(){ return Array.from(itemsHost.querySelectorAll('[data-ns53-item]')).map(el=>{ const out={}; el.querySelectorAll('[data-f]').forEach(f=>out[f.dataset.f]=f.value||''); return out; }); }
    box.querySelector('[data-ns53-add]').onclick=()=>{ const next=readItems(); next.push(typeSel.value==='teachers'?{name:'',summary:'',imageUrl:'',detail:''}:{classId:'',label:'',imageUrl:'',summary:'',detail:''}); bodyField.value=serialize({type:typeSel.value,items:next}, box.querySelector('[data-ns53-rest]').value); renderItems(); };
    box.querySelector('[data-ns53-pack]').onclick=()=>{ if(typeSel.value==='generic'){ bodyField.value=box.querySelector('[data-ns53-rest]').value||''; } else { bodyField.value=serialize({type:typeSel.value,items:readItems()}, box.querySelector('[data-ns53-rest]').value); } alert('페이지 내용 필드에 반영했습니다. 아래의 "학원안내 저장"까지 눌러야 실제 저장됩니다.'); };
    typeSel.onchange=()=>{ const meta=parseMeta(bodyField.value)||{items:[]}; bodyField.value=typeSel.value==='generic' ? box.querySelector('[data-ns53-rest]').value||'' : serialize({type:typeSel.value,items:Array.isArray(meta.items)?meta.items:[]}, box.querySelector('[data-ns53-rest]').value); renderItems(); };
    renderItems(); }
  function scan(){ pageRows().forEach(ensureOnRow); }
  const mo=new MutationObserver(()=>scan());
  function boot(){ scan(); mo.observe(document.documentElement,{childList:true,subtree:true}); }
  if(document.readyState==='loading') document.addEventListener('DOMContentLoaded',boot,{once:true}); else boot();
})(window);